future: true
permalink: /:title/
url: http://carlsome.github.io
name: Carl
author: Carl
qq: 245221442
email: 245221442@qq.com

duoshuo: 
beian: 
cnzz: 
weibo: 
github: CarlSome
about: "这里是Carl的个人博客，创建于 2018 年。"

safe: true
paginate: 20
